_wandb:
    value:
        cli_version: 0.25.0
        e:
            uil6adsn5jt5n0lwdrsdlkyniaivkndk:
                args:
                    - --data_dir=prep_data/train
                    - --meta_data=prep_data/metadata.csv
                    - --target=mri
                    - --training_mode=train
                    - --conditioning_image=none
                    - --resume_checkpoint=
                    - --resume_step=0
                    - --image_size=256
                    - --use_fp16=True
                    - --use_checkpoint=True
                    - --microbatch=1
                    - --auto_vram=True
                    - --lr=1e-5
                    - --lambda_mask=10.0
                    - --save_interval=5000
                    - --num_workers=4
                    - --devices=0
                    - --beta_min=0.1
                    - --beta_max=20.0
                    - --dataset=mri
                    - --num_channels=32
                    - --class_cond=False
                    - --num_res_blocks=2
                    - --num_heads=1
                    - --timestep_respacing=
                    - --learn_sigma=False
                    - --use_scale_shift_norm=True
                    - --attention_resolutions=
                    - --channel_mult=1,2,2,4,4,4
                    - --diffusion_steps=2
                    - --noise_schedule=vp_sde
                    - --rescale_learned_sigmas=False
                    - --rescale_timesteps=False
                    - --dims=3
                    - --batch_size=1
                    - --num_groups=32
                    - --in_channels=8
                    - --out_channels=8
                    - --bottleneck_attention=False
                    - --resample_2d=False
                    - --renormalize=True
                    - --additive_skips=False
                    - --use_freq=True
                    - --predict_xstart=True
                    - --use_wandb
                    - "True"
                    - --wandb_project
                    - mri_wavelet
                    - --wandb_entity
                    - dklaaby
                    - --wandb_run_name
                    - test_only_brain_and_autovram
                codePath: scripts/generation_train.py
                codePathLocal: scripts/generation_train.py
                email: dklaaby@gmail.com
                executable: /home/daniel/micromamba/envs/wdm/bin/python
                git:
                    commit: 87bea0ca456823b5f6d24bc544b0a5ed530a13b1
                    remote: git@github.com:Dani440b/tooth-diffusion.git
                host: fedora
                os: Linux-6.18.7-200.fc43.x86_64-x86_64-with-glibc2.42
                program: /home/daniel/Documents/thesis/tooth-diffusion/scripts/generation_train.py
                python: CPython 3.10.13
                root: /home/daniel/Documents/thesis/tooth-diffusion
                startedAt: "2026-02-16T14:57:26.064860Z"
                writerId: uil6adsn5jt5n0lwdrsdlkyniaivkndk
        m: []
        python_version: 3.10.13
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 13
                - 16
            "4": 3.10.13
            "5": 0.25.0
            "12": 0.25.0
            "13": linux-x86_64
additive_skips:
    value: false
attention_resolutions:
    value: ""
auto_vram:
    value: true
batch_size:
    value: 1
beta_max:
    value: 20
beta_min:
    value: 0.1
bottleneck_attention:
    value: false
channel_mult:
    value: 1,1,2,2,4,4
class_cond:
    value: false
conditioning_image:
    value: none
data_dir:
    value: prep_data/train
dataset:
    value: mri
devices:
    value:
        - "0"
diffusion_steps:
    value: 2
dims:
    value: 3
dropout:
    value: 0
ema_rate:
    value: "0.9999"
fp16_scale_growth:
    value: 0.001
image_size:
    value: 256
in_channels:
    value: 8
lambda_mask:
    value: 10
learn_sigma:
    value: false
log_interval:
    value: 100
lr:
    value: 1e-05
lr_anneal_steps:
    value: 0
meta_data:
    value: prep_data/metadata.csv
microbatch:
    value: 1
mode:
    value: default
noise_schedule:
    value: vp_sde
num_channels:
    value: 16
num_groups:
    value: 32
num_head_channels:
    value: -1
num_heads:
    value: 1
num_heads_upsample:
    value: -1
num_res_blocks:
    value: 2
num_workers:
    value: 4
out_channels:
    value: 8
predict_xstart:
    value: true
renormalize:
    value: true
resample_2d:
    value: false
resblock_updown:
    value: true
rescale_learned_sigmas:
    value: false
rescale_timesteps:
    value: false
resume_checkpoint:
    value: ""
resume_step:
    value: 0
save_interval:
    value: 5000
schedule_sampler:
    value: uniform
seed:
    value: 0
target:
    value: mri
tensorboard_path:
    value: ""
timestep_respacing:
    value: ""
training_mode:
    value: train
use_checkpoint:
    value: true
use_fp16:
    value: true
use_freq:
    value: true
use_kl:
    value: false
use_new_attention_order:
    value: false
use_scale_shift_norm:
    value: true
use_tensorboard:
    value: true
use_wandb:
    value: true
wandb_entity:
    value: dklaaby
wandb_project:
    value: mri_wavelet
wandb_run_name:
    value: test_only_brain_and_autovram
weight_decay:
    value: 0
